// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQN5zZZO9leIT4oiimDEymquLogwGLRg',
    appId: '1:596279565346:web:9baa3ddc0e10056c107e7b',
    messagingSenderId: '596279565346',
    projectId: 'transmobiile',
    authDomain: 'transmobiile.firebaseapp.com',
    storageBucket: 'transmobiile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKJY9LcYZeSH0LSUHFsCkDdS9t2-oDfY',
    appId: '1:596279565346:android:b2a0354ce5ee50cc107e7b',
    messagingSenderId: '596279565346',
    projectId: 'transmobiile',
    storageBucket: 'transmobiile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQdLYPYnxpeK3YCKKh__O8ftDf-iPkTM',
    appId: '1:596279565346:ios:9318f71477941547107e7b',
    messagingSenderId: '596279565346',
    projectId: 'transmobiile',
    storageBucket: 'transmobiile.appspot.com',
    iosBundleId: 'com.example.transmobile',
  );
}
